### ISSUE TITLE
Debugging "no valid signing keys for delegation roles" error

### ISSUE THREAD

**Issue by ruimarinho** [docker/notary#1049]
I'm pretty sure the problem is between the chair and the computer here, but I wanted to get a better understanding of how notary works so that I can easily pinpoint solutions when something like this happens.

I got the delegation working for the `targets/releases` role (using `docker:dind` to test the pushes) but somehow I lost the ability of signing releases on the host machine with root (YubiKey).

The error is:

```
Failed to sign "foo.com/bar":1.0.0 - no valid signing keys for delegation roles
no valid signing keys for delegation roles
```

If the list delegations on that GUN, it's true that I don't see my delegation role there (just the other's machine one, which continues to be able to push).

However, `notary <…> key list` gives me this:

```
targets    ...oo.com/bar    05209e8a98a5f584e1e13ec088670d4c49ab7db11c9156b77542f1588c099a09    /Users/foobar/.docker/trust/private
```

That same key id appears when I use `-D -v` and do `delegation list foo.com/bar`:

```
DEBU[0000] Loading targets...
DEBU[0000] targets role has key IDs: 05209e8a98a5f584e1e13ec088670d4c49ab7db11c9156b77542f1588c099a09
DEBU[0000] verifying signature for key ID: 05209e8a98a5f584e1e13ec088670d4c49ab7db11c9156b77542f1588c099a09
DEBU[0000] successfully verified cached targets
```

Where did the link get broken? Could it have been an experimentation with snapshot key rotation?

**Comment by riyazdf** [comment]
hi @ruimarinho, we'd be happy to help!

Docker Content Trust has an opinionated view of delegations because once you've added delegations for a role, it will attempt to only sign tags into a delegation.
So the error you're seeing for `foo.com/bar` is saying that Docker Content Trust knows that there are delegations set up for this repository and it can't find any delegation keys to sign with on the local machine.

Do you have a delegation key on that box?  It appears from the `notary key list` output you've provided that you only have the `targets` key.  In this case, you could generate and add a new key to your delegation and you can do this because you have the `targets` key locally and the snapshot key is rotated to the server.  You could then use this newly added delegation key to sign `foo.com/bar` with Docker Content Trust on your  machine.

Does this help?   Please let us know if there's anything that is unclear.  Here are [the docs for more information about Docker Content Trust with delegations](https://docs.docker.com/engine/security/trust/trust_delegation/#/docker-push-behavior).

**Comment by ruimarinho** [comment]
I don't have a specific delegation key for this GUN locally. If I attempt to generate, sign and then import one locally, it tells me that my YubiKey only supports storing root keys (`ERRO[0014] failed to import key to store: yubikey only supports storing root keys, got user for key: 034…`), as expected.

I've read the DCT delegation does but it says, under the `docker push` header, that *Docker Engine will attempt to sign and push with the targets/releases delegation if it exists. If it does not, the targets key will be used to sign the tag, if the key is available*. Since I have the `targets` key available for this repository, as `notary delegation list <GUN>` shows, why would I need to generate a new delegation for signing locally?

**Comment by riyazdf** [comment]
Does `notary delegation list <GUN>` show a `targets/releases` role?
If so, you'll need that specified delegation key locally in order to sign with DCT.  If you'd prefer to use another key, you can generate a new one and import it.

As of now, only root keys can be stored in yubikeys though we're tracking an issue here https://github.com/docker/notary/issues/306 to expand this to more keys.  Other keys live on disk in the `$trust_dir/private` subdirectory

What does `notary delegation list <GUN>` show for `targets/releases` key IDs?  And does it match `05209e8a98a5f584e1e13ec088670d4c49ab7db11c9156b77542f1588c099a09`?  I have a hunch that your delegation key might be different since we require a certificate (unless you signed one for the same targets private key yourself).

**Comment by ruimarinho** [comment]
I'll get to your comment in a few seconds, but just found on the repository advanced usage .md:

> If delegation roles exist but the user does not have signing keys, the push will fail. If no delegation roles exist, the push will attempt to sign with the base `targets` role.

Since I've added a delegation role, I think Docker 1.11 will stop using the `targets` role.

**Comment by riyazdf** [comment]
@ruimarinho: yes that's correct - the `docker push` documentation linked above is trying to say the same thing but the wording is a little more confusing because it does not say "role" explicitly.

So I think you should try adding a new key for this host to the delegation role (or using the existing delegation key, if that's ok in your set up) and that should work for your `DOCKER_CONTENT_TRUST=1` push

**Comment by ruimarinho** [comment]
> Does notary delegation list <GUN> show a targets/releases role?

Only on container B (the one without the root key). Container A (root + YubiKey) shows:

```
ROLE                PATHS             KEY IDS                                                             THRESHOLD
----                -----             -------                                                             ---------
targets/releases    "" <all paths>    724854ea9acad6feb7423cd5dfddd856e09e671f7df8b9587c2dd50abf744aee    1
```

This is the delegation key id I've generated on container B and imported "locally" (container A). So, in other words, this isn't an usable signing key as I don't have it's private key.

> As of now, only root keys can be stored in yubikeys though we're tracking an issue here #306 to expand this to more keys. Other keys live on disk in the $trust_dir/private subdirectory

Looks like even though the error is output, it successfully imported a delegation key generated locally (container A) to `$trust_dir/private`.

However, I'm unable to import the certificate -- `fatal: unable to parse valid public key certificate from PEM file delegation.crt: invalid certificate: certificate with CN  uses invalid SHA1 signature algorithm`.

> What does notary delegation list <GUN> show for targets/releases key IDs?

Just the `724854ea9acad6feb7423cd5dfddd856e09e671f7df8b9587c2dd50abf744aee` (container's B delegation key). No sign of my `targets` key `05209e8a98a5f584e1e13ec088670d4c49ab7db11c9156b77542f1588c099a09` (which continues to be visible via `notary key list` with the correct GUN).

**Comment by ruimarinho** [comment]
Interesting. On container A, I'm getting hit by https://github.com/docker/notary/blob/eb214782470e4913e5215df96e24aa59c36ca045/tuf/utils/x509.go#L287-L290 (specifically, `x509.ECDSAWithSHA1`).

**Comment by ruimarinho** [comment]
Ok, just fixed local key generation by switching to openssl 1.0.2. However, I need help understanding if what I did makes sense:

1. I've generated a `.csr` based on my `targets` key for this GUN `05209e8a98a5f584e1e13ec088670d4c49ab7db11c9156b77542f1588c099a09`.
2. I've self-signed the .csr with this same private key and created the certificate.
3. I've imported the delegation crt with the `targets/releases` role for this GUN.

Does it make sense to re-use the `targets` private key or it is actually a security concern? What would be the benefits of generating yet another key (`--role user`?) and then import it as a delegation key?

**Comment by riyazdf** [comment]
@ruimarinho: you should not re-use the `targets` private key - that key has higher privilege than any delegation key because it can manage delegations (add/remove/edit delegation roles).  It's advised to generate a new key

**Comment by ruimarinho** [comment]
Ok, so for a single repository pushed by multiple organisation collaborators, I need:

- One root key which is shared among repositories.
- One `targets` key so I can manage delegations.
- One `targets/releases` per user doing pushes, including myself.

Is this correct, i.e. 3 passphrases per repository?

**Comment by riyazdf** [comment]
@ruimarinho: that setup makes sense.

I'll expand on your setup by saying that the `root` and `targets` key are to be held by an administrator for the repository, and there can be a `targets/releases` key for each collaborator (each with a unique passphrase).

**Comment by ruimarinho** [comment]
Ok. Since I cannot backup my root key, considering it's generated on the YubiKey (and I like that it never leaves it), can I add other collaborators as administrators to a repository in case my YubiKey gets stolen?

**Comment by riyazdf** [comment]
@ruimarinho: notary/Docker Content Trust should also leave an encrypted copy of the `root` key material on disk, so that you can back it up somewhere safe.

If your collaborators are only going to be managing delegation roles, it's sufficient to only share the `targets` key since that key has privilege over delegation role management.

**Comment by ruimarinho** [comment]
I've generated the root key via `yubico-piv-tool`, so while notary/DCT knows it exists, it's not able to read it.

The CI system will be responsible for most of the signed builds using a delegation role, but sometimes a manual signed build might be necessary. This means I have no option but to generate/import one `targets/releases` key per collaborator doing manual pushes outside our regular CI setup.

Also, if my previous comment proves incorrect - i.e. a single `targets` key could suffice, by sharing you mean sending them the private key and agree on a shared secret (passphrase)?

**Comment by endophage** [comment]
> The CI system will be responsible for most of the signed builds using a delegation role, but 
> sometimes a manual signed build might be necessary. This means I have no option but to 
> generate/import one targets/releases key per collaborator doing manual pushes outside our 
> regular CI setup.

Yes, this is correct. Ideally those collaborators would generate their own keys and send you just the public component.

**Comment by ruimarinho** [comment]
Right, the private key would not leave their work station. What's the risk in one collaborator re-using the same delegation key over and over again? It might be possible to detect that if I'm paying attention to the key ids, but there's nothing on notary preventing that from happening, correct?

**Comment by ruimarinho** [comment]
@endophage it looks like delegation key re-use is actually supposed to happen. From docs: *Note that for root and delegation keys, the `--gun` flag is ignored because these keys can be shared across GUNs.* Can you confirm this?

**Comment by endophage** [comment]
You will need to determine your own security model to decide whether you want to re-use delegation keys across repositories. In many cases it makes sense and that's why we support it.

If however your security model does not allow for users to be identified across repos, you would not want to re-use delegation keys. This may also be affected by whether your repositories are behind some form of authorization gateway, either by integrating with the supported token based auth, or by placing some form of authorizing proxy in front of your notary service. If this effectively makes all repos private within your organization, and your security model does not require anonymity within your organization, key re-use may still be acceptable.

**Comment by ruimarinho** [comment]
In my case, anonymity is not a goal, so considering we have token based auth, I believe key re-use is acceptable then. Thanks for clarifying this.

**Comment by kyrogue** [comment]
hello, may i know what is the command to add the delegation key into docker? im trying 

`docker trust key load mykey.key`

But it seems to still report 
```
Signing and pushing trust metadata
failed to sign GUN: no valid signing keys for delegation roles
```

**Comment by williamdes** [comment]
I had this issue until I loaded the key from a file that had as name the key ID
See: https://github.com/sudo-bot/action-docker-sign/commit/68258f69680f5c65f5ac6053a67557323c106fb1
