### ISSUE TITLE
Documentation: it is unclear where image is signed originally

### ISSUE THREAD

**Issue by artsf** [docker/notary#1131]
Neither the architecture doc, not TUF make it clear that image is signed on originating machine, NOT in notary server.

**Comment by endophage** [comment]
We can update docs here as it relates specifically to Notary but you may also want to file an issue on the [docker docs](https://github.com/docker/docker.github.io) requesting more in depth documentation on the Docker Content Trust architecture and signing process.

**Comment by artsf** [comment]
Moved.

**Comment by Simkiw** [comment]
Hi guys,

I've tried to get rid of my confusions, but couldn't so far.
Between docker and notary documentation, I don't seem to fully understand how things are happening.
In terms of keys, the ones that sign the image are either the target key or the delegating key.
From what i've read, they work in different manners:
- target key is generated by docker I think, and signs the image after it is pushed to the registry. Is the key stored in notary? Because it also said that it should be kept to the owner and should not be shared unless with contributors. And in this case, how can this image be verified?
- in notary doc, I've seen a diagram of keys hierarchy. It appears that a delegating key is made signed/created/made by target key (not sure which term to use). It makes me wonder, are delegating private key and tagging key the same? In terms of verification, Docker doc says it only pushed the public delegating key which serves to verify the image. But in notary, I think it always stores the private key.

I'm trying to understand the flow as well as the definition, what is what? who signs and who stores? how verification happens? the specific keys involved? the use cases (I noted that delegation gives the ability to sign images to other contributors without sharing the target key for instance)

Thank you for your time
