### ISSUE TITLE
Confusion over current time in isExpired()

### ISSUE THREAD

**Issue by DanBarychev** [docker/notary#1192]
In [isExpired()](https://github.com/docker/notary/blob/master/tuf/signed/verify.go#L23-L25), called by [verifyExpiry()](https://github.com/docker/notary/blob/master/tuf/signed/verify.go#L28-L34), Notary checks if the expiration time of the metadata it is trying to verify is before the current time, represented by `time.Now()`. What I don't understand is what `time.Now()` refers to for the current time. I know that it represents the time elapsed since the Unix epoch, but does it get this elapsed time using the system time or some outside source. If it's using the system time, isn't this unsafe since whoever calls `notary verify` can have a completely custom system time that allows the verification of out-of-date metadata?

**Comment by endophage** [comment]
`time.now()` is implemented in assembly, here's the version for Mac OS https://github.com/golang/go/commit/e4371fb179ad69cbd057f2430120843948e09f2f#diff-f8bb5330396b58ac2494db8dc42f6b2bL117

It will as far as I understand grab the system time and yes this could result in data being trusted beyond its intended time. One way in which this is handled is the version numbers, so that at a minimum, nobody can be downgraded to an older version of the TUF data than they have already seen. 

The primary layer of protection comes from the system itself. On Linux, changing the system time is a privileged operation. Using tools such as NTP, and maintaining the correct permissions on changing the time, is considered sufficient. The attacker model does not include the user changing the time and verifying something that shouldn't be valid. The attacker model needs to account for a malicious adversary causing your system time to be changed such that you unknowingly accept out of date information.

If somebody is calling `notary verify`, it's in their interest to remain secure, and therefore use the correct time. Also note that expiry times in notary include a timezone (`i.e. 2025-08-07T20:36:33.117452-07:00`, the `-07:00` on the end indicates the time is UTC -7 hours), so we can correctly verify the expiry even if the publisher and consumer are in different timezones.

**Comment by DanBarychev** [comment]
@endophage Thank you so much for your answers, this definitely clears things up alot (especially the note about expiry time zones)

**Comment by endophage** [comment]
No problem!
