### ISSUE TITLE
Allow notary-server to perform timestamping

### ISSUE THREAD

**Issue by NathanMcCauley** [docker/notary#17]
notary-server should have a facility to timestamp the TUF metadata files so that publishers do not need to be constantly signing their content.

**Comment by dmp42** [comment]
Done.

**Comment by lewiada** [comment]
I do not understand the motivation for this.  Anytime I am going to push an image to a docker repo, it will involve signing using the targets (or delegated targets) key.  What is the UX benefit to having the timestamp key online, that justifies the weakened security of the timestamp key by being kept on-line?  I understand the timestamp key is the least sensitive of the bunch, but I'm not seeing gain from the trade-off in security.  What am I missing?

**Comment by cyli** [comment]
@lewiada The timestamp key expires early, so you will have to come back and re-sign the timestamp file every 2 weeks even if you aren't pushing any images.  If your timestamp expires, everything you've signed into your repo becomes invalid until push a new signed timestamp.  

It is a usability tradeoff; rather than you having to manually re-certify that your signed content so often, the server does it for you if you are not around.

**Comment by lewiada** [comment]
do you mean the timestamp.json *file* expires every two weeks?  If the timestamp *key* expired every two weeks then a new root.json file would need to be created which would involve taking the root key out.  

Which makes me wonder, how long is the timestamp key lived for?  I suppose I would need to proactively rotate it to avoid it expiring and things breaking, but I'm not sure what the actual lifetime is.

**Comment by riyazdf** [comment]
@lewiada - correct, it's the timestamp file that expires every two weeks.  We're working on a [best practices doc](https://github.com/docker/notary/pull/955/files#diff-b060354fe719f76e1c05c20d54fb2764R114) which aims to capture this information and provide operation suggestions.  Please let us know if there's anything we should add!

As for the timestamp key itself - it does not have an explicit expiry time, though it will become invalid if the root file that specifies it becomes expired or otherwise invalid.

**Comment by cyli** [comment]
@lewiada Ah sorry, yes I meant the file.
