### ISSUE TITLE
Weird behaviour about notary

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#252]
I have three hosts,

**host1** with ENV TRUST:
```
$ export DOCKER_CONTENT_TRUST=1
$ export DOCKER_CONTENT_TRUST_SERVER=https://notaryserver:4443

$ docker tag ubuntu notary-registry:5000/testimage:latest
$ docker push  notary-registry:5000/testimage:latest
```

**host2** without EVN TRUST:
```
$ docker tag busybox notary-registry:5000/testimage:latest
$ docker push  notary-registry:5000/testimage:latest
```

**host3** with ENV TRUST:
```
$ export DOCKER_CONTENT_TRUST=1
$ export DOCKER_CONTENT_TRUST_SERVER=https://notaryserver:4443

$ docker pull  notary-registry:5000/testimage:latest
```
It is the image from host1, shouldn't it from host2 since host2 do the push things after the host1 with the same tag `notary-registry:5000/testimage:latest`?

And then I do another test,

**host3 without** ENV TRUST:
```
$ unset DOCKER_CONTENT_TRUST
$ unset export DOCKER_CONTENT_TRUST_SERVER

$ docker pull  notary-registry:5000/testimage:latest
```
It is the image from host2.

Is this intended or a bug?

**Comment by cyli** [comment]
This is intended behavior.

In the case of host1, when you pushed, it should have asked you to sign the image you pushed (and/or maybe create a root key/targets key, and asked you for passwords for them), right?  The output should have ended with `Signing and pushing trust metadata`?

Since that image is signed, you can pull that image on any client with `DOCKER_CONTENT_TRUST` enabled.  Setting `DOCKER_CONTENT_TRUST` in host3 means that it will only pull signed images (the push from host 2 was not signed, but the push from host 1 was, so it pulled host 1's) of the right tag.

On host 3 without `DOCKER_CONTENT_TRUST` it just pulls the latest image, with or without signing, so it pulled host 2's image.

https://docs.docker.com/security/trust/content_trust/#survey-of-typical-content-trust-operations might clarify how the individual operations work.  :)

**Comment by HuKeping** [comment]
Thanks @cyli , this helps me a lot .
