### ISSUE TITLE
Incorrect handling of non-existing remote repositories

### ISSUE THREAD

**Issue by diogomonica** [docker/notary#286]
dc3 exists, dc6 does not and neither does dc64. Yet, dc6 sends an ugly JSON error, and dc64 sends a "cannot reach server", when both should just say that there is no metadata. The difference between them is that dc6 was `notary init docker.io/diogomonica/dc6` and dc64 was not.
```
➜  ~  notary list docker.io/diogomonica/dc6
ERRO[0002] Client Update (Timestamp): unexpected end of JSON input
ERRO[0002] client Update (Root):Unable to reach trust server at this time: 401.
* fatal: Unable to reach trust server at this time: 401.
➜  ~  notary list docker.io/diogomonica/dc64
* fatal: Unable to reach trust server at this time: 401.
➜  ~  notary list docker.io/diogomonica/dc3
latest 9cea54f9603e3345aceaa31a4b1c9d148fcc5d48f18b684513b31d88e7866328 1608
```

**Comment by endophage** [comment]
Context because we encountered this again today:

This is a function of the token server. It will not issue a read token for a repository that doesn't exist. At a guess I would say this is to prevent leaking names of repositories that exist but you don't have access to (one could determine a name existed based on not being issued a token).

With that behaviour in the token server, notary is incapable of distinguishing a user without access, vs a repository that doesn't exist.

**Comment by riyazdf** [comment]
It seems that the error has improved with this commit https://github.com/docker/notary/commit/d4820c575666be57966a64619f0c96ebe72c305b, as I'm unable to reproduce the original message on my current notary binary.

When I try to reproduce on my local docker-compose setup off of the latest master:

```
$ notary list docker.io/diogomonica/dc6
* fatal: notary-server:4443 does not have trust data for docker.io/diogomonica/dc6
```

I like this error much more since we actually report that the trust data doesn't exist, should we update the error any more?

**Comment by diogomonica** [comment]
No, this is seems solved.
