### ISSUE TITLE
A little confuse about these keys

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#317]
Hi there,

Per the docs of Notary, the content publisher holds a private key which is used to sign the images which I supposed to be the `tagging` key, and `tagging` key was generated by a `offline` key. 

So what is the relationship  between the `offline`/`tagging` key and the so called private key?

> Consumers, having acquired the publisher's public key, relying only on the publisher's key to determine the validity and integrity of the received content.

So what's the relationship between the `offline`/`tagging` key and the public key?

**Comment by cyli** [comment]
I think you got "tagging key" from  [this article](https://blog.docker.com/2015/08/content-trust-docker-1-8/)?

And the quote about the public key is from the README?

If so, I think the combination might be a little confusing, so I'm going into a little more detail on the background just to try to establish some common terminology (apologies you already know most of this information):

--- 

We use [public/private key pairs](https://en.wikipedia.org/wiki/Public-key_cryptography#Understanding) for signing everything in TUF.  The public key is viewable by everyone, and [are specified in the metadata files](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L474) - they are used by consumers to verify the signatures.

[The private key of the key pair is used to generate signatures, and the public key of the key pair is used to verify signatures](https://en.wikipedia.org/wiki/Digital_signature#Definition)

TUF has [5 top level roles](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L214) - and Notary supports 4, and generates one key pair for each:

- the root/offline key pair (the user is responsible for keeping the private key of the pair) key is used to sign the root role metadata
- the targets key pair (the user is responsible for keeping the private key of the pair) is used to sign the targets role metadata - this contains the tagging data
- the snapshot key pair (the user is responsible for keeping the private key of the pair for now) is used to sign the snapshot role metadata - this tells you what the *latest* tagging data is
- the timestamp role (the server is responsible for keeping the private key of the pair).

---

The offline key referred to in the README and the article is the private key of the root key pair.  The consumer gets the public part (from the metadata), saves it, and uses it to verify the root metadata now and in the future (trust on first use).  This is the "publisher's public key" referred to in your quote and the README.

The tagging key referred to in [this article](https://blog.docker.com/2015/08/content-trust-docker-1-8/) is the private keys of the targets and snapshots key pairs.  I think it's called the tagging key (singular) in the article because (1) they can be the same key, but they're not in our system and  (2) they are both needed on the client side to tag data.

They also have public parts, and the consumer gets the public parts [from the root metadata](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L356), and can use them to verify the targets and snapshots metadata.  Unlike the root public key though, the consumer does not need to save or pin these - they can be rotated out transparently.

**Comment by HuKeping** [comment]
Impressive! Thanks very much @cyli and  those links to the docs of tuf is very helpful!
