### ISSUE TITLE
Reserialize metadata JSON bytes before storing in DB

### ISSUE THREAD

**Issue by cyli** [docker/notary#366]
This way if the user sends us extra fields (either just garbage or their own tuf extensions), only the data we support will be stored in the DB.

**Comment by endophage** [comment]
I've found 2 problems with doing this:

1. It turns out clients aren't using canonical json for the `data.Signed` -> `[]byte` final serialization. This makes it problematic to consistently reserialize on the server. I've addressed this in #426

2. If a client is managing the snapshot key itself, we can't (or at least there's no point) reserialize targets/root JSON because if it changes we won't be able to update the hash/size in the snapshot file.

**Comment by mtrmac** [comment]
If the server drops JSON fields received from the author, and therefore cannot reproduce the same JSON when sending it to other clients, AFAICS the author’s signature cannot validate. What am I missing?

**Comment by endophage** [comment]
@mtrmac that is also true. I should close this, we're not looking to do it any more, but I also need to open another issue to track fixing the canonical serialization problem (we can't reserialize but we have determined a path to get to canonical serialization for all TUF data.
