### ISSUE TITLE
Multiple Notary servers support

### ISSUE THREAD

**Issue by pgkelley4** [docker/notary#402]
With the docker registry you can setup registries in multiple regions backed by the same S3 bucket. Similarly, is it possible to run multiple Notary servers and signers with a single backend store?

Is any other type of replication between Notary servers being considered?

Or is this less of an issue because all the information in the notary server is public and can be more easily exposed for whoever needs it?

Sorry if this is the wrong place for this question. The google group is private and this information should probably be easy to find.

**Comment by diogomonica** [comment]
Peter, thank you for the issue.

It is absolutely possible to run multiple notary servers and signers with a single backend store. We do it ourselves.

Technically the signers don't have to share the backend database with the server. Signer and server are completely independent, except for the fact that the servers need access to the RPC endpoint of the signers (in order to create keys and sign metadata).

As you point out, it is easier to have a read-only replica of notary-server data (because it's essentially public data). You would obviously be using potentially not up-to-date trusted data, but notary guarantees that the oldest this data can be is 2 weeks. You can actually do this by hosting static root.json, targets.json, snapshot.json and timestamp.json files on a web-server. As long as you have some kind of job refreshing the latest information, this could be used as a read-only replica of notary.

Right now we recommend that replication is done at the DB level (mysql replication, for example).

**Comment by HuKeping** [comment]
Hi @pgkelley4 , do you mean something like:

```
--------- load balancer----------
  |             |               |

Notary1   Notaty2  ...    Notary n
 \              |                /
   \            |              / 
     \          |            /
          MySQL cluster
```

**Comment by pgkelley4** [comment]
@HuKeping Yes, that is the first scenario I attempting to describe.

**Comment by HuKeping** [comment]
Since Notary is almost stateless and thus it can be easily be deployed as a Notary-cluster.  So I think maybe this is what the Ops needs to be considered about.

**Comment by endophage** [comment]
@pgkelley4 we've recently updated the official notary docs with the aim of clearing up some of these questions. Could you take a look, particularly at the [Running a Notary service](https://docs.docker.com/notary/running_a_service/) page and let us know if it answers your question? There's a section right at the end of that page, High Availability, that includes an architecture diagram of a simple HA deployment with multiple servers and signers.

**Comment by pgkelley4** [comment]
@endophage Yes, it does. Thank you.

**Comment by endophage** [comment]
Fantastic! I'm going to close this. Please let us know if there are any ways we can improve the docs further in a new issue.
