### ISSUE TITLE
Ensure support for unencrypted private keys generated outside of notary

### ISSUE THREAD

**Issue by diogomonica** [docker/notary#476]
- Try creating a PEM encoded private key with OpenSSL
- Create a X509 certificate with it
- Import the x509 certificate as a delegated key
- Copy the openssl created private key to `tuf_keys`
- Attempt to sign with Docker

**Comment by NathanMcCauley** [comment]
Do we actually want to support unencrypted keys? We don't any other keys to be unencrypted.

**Comment by diogomonica** [comment]
@NathanMcCauley my idea here is that if you went through the trouble of creating a key by hand outside of notary, didn't encrypt it, but still put it in the right directory, the expectation is that it should work.

What if they know what they are doing, and this is an in-memory filesystem that doesn't persist anything?

I don't feel strongly about it thought, and I'm fine either way.

**Comment by riyazdf** [comment]
I've verified that this works as expected with notary with both encrypted and unencrypted private keys, will test Docker signing in-depth tomorrow.

I think it'll be helpful to make it easy to import the delegation key with the proper canonical key ID and role headers, since notary will look for this specifically -- this was probably the hardest part of setting this up, it wasn't as easy as just dropping in the key.  I'll look into a notary CLI command to make this easier

**Comment by diogomonica** [comment]
@riyazdf probably not worth the effort. Let's prioritize a flat keystore that loads all the files under private/, and allows us to simply drop keys inside of any directory. We should still keep our current file structure (root keys, tuf keys, etc), but the keystore object should load every valid key, and allow lookup by ID without the GUN being needed.

**Comment by diogomonica** [comment]
@riyazdf and feel free to close this issue if it was satisfactorily validated. Also save the steps that you took for validation for our client docs.

**Comment by endophage** [comment]
Just re-validated with @NathanMcCauley
