### ISSUE TITLE
Notary delegation remove allows removal even when there are no delegations

### ISSUE THREAD

**Issue by diogomonica** [docker/notary#489]
If there is nothing to be deleted, we shouldn't be creating changelists for it.

```
➜  notary git:(master) notary delegation remove docker.io/diogomonica/testingnot1 targets/diogo

Are you sure you want to remove all data for this delegation? (yes/no)
yes

Forced removal (including all keys and paths) of delegation role targets/diogo to repository "docker.io/diogomonica/testingnot1" staged for next publish.
Removal of delegation role targets/diogo with keys [] and paths [], to repository "docker.io/diogomonica/testingnot1" staged for next publish.
```

```
➜  notary git:(master) notary status docker.io/diogomonica/testingnot1
Unpublished changes for docker.io/diogomonica/testingnot1:

action    scope     type        path
----------------------------------------------------
delete    targets/diogodelegation  
```

**Comment by riyazdf** [comment]
This one is tricky because `notary delegation remove` is completely offline so we don't know for certain if the delegation exists or not.  `notary remove` has the same behavior, actually:

```
$ notary remove GUN does_not_exist
Removal of does_not_exist from GUN staged for next publish.

$ notary status GUN
Unpublished changes for GUN:

action    scope     type        path
----------------------------------------------------
delete    targets   target      does_not_exist
```

I think these commands should be consistent with each other -- so maybe they both do an online check for existence first, or stay offline?  For both, on a publish they silently no-op:

```
$ notary publish GUN
Pushing changes to GUN
Enter passphrase for targets key with ID 09a5cd8 (GUN):
$ notary list GUN

No targets present in this repository.
```

**Comment by endophage** [comment]
Discussed this out of band with @diogomonica briefly last night. My preferred paradigm in this scenario is that a delete on something that doesn't exist is a no-op and is messaged as a success. There are arguments for doing otherwise as it could be that the user has typoed the name, however, if users aren't being careful about their input, they could delete content they didn't mean to so I find that a weak argument for failing loudly.

**Comment by endophage** [comment]
@diogomonica @riyazdf @NathanMcCauley @cyli 

Do we feel OK closing this on the basis that deleting something that doesn't exist should be considered a successful no-op?

**Comment by riyazdf** [comment]
I agree with @endophage and think we should close this
