### ISSUE TITLE
Add check of cert when uploading root.json

### ISSUE THREAD

**Issue by endophage** [docker/notary#52]
We should check that the name in the cert matches the provided GUN when a user uploads a root.json.

**Comment by diogomonica** [comment]
@endophage is this still not true?

**Comment by endophage** [comment]
I believe so. I don't see a check for the certificate being correct within the server validation code.

**Comment by cyli** [comment]
@endophage It seems like the keystoremanager already sort of has this:  https://github.com/docker/notary/blob/master/keystoremanager/keystoremanager.go#L217

However, it to be fine with the root.json having some invalid certificates, so long as there is at least one valid one?  Is the root.json allowed to have invalid certs?  Even certs with the wrong GUN?

(Although as per #181 maybe we should try to unify some of this code?  Is there a reason the client should not check all the things that the server checks?)

**Comment by mtrmac** [comment]
Is this for a security purpose, or just ease of use?

AFAICS if the client to the Notary server is properly authorized to upload for a specific GUN, and they want to upload garbage to the server to screw up their repo, well, we can let them; the important thing is that garbage served by the Notary server to clients (whether caused by a malicious server operator or by a malicious uploader) can not attack the clients (e.g. by planting trusted certificates for different GUN, which is what the keystoremanager bit quoted above prevents).

That’s not to say that code shouldn’t be added when it improves “only” ease of use but not security; I’d just like it to be clear which of these is being addressed (both for the general design and for individual lines of code). Otherwise, sooner or later, someone will add a $security_feature which, for security, relies on an $ease_of_use_functionality, and later someone else will improve, replace or otherwise remove the $ease_of_use_functionality, breaking $security_feature.

**Comment by endophage** [comment]
@mtrmac I'm of the opinion that the server should not accept data that a client will not be able to successfully pull. Especially in the case where the publish action essentially does a rebase, this could leave a repository in a state where manual cleanup is required to enable the owner to continue to be able to publish. Given I also maintain Docker's instance of Notary, I have an aggressive interest in data integrity and cleanliness.

@cyli It would be better if all the certs have the right GUN. Failing that, as long as we only use certs with the correct GUN to validate signatures (and I'm not sure we're consistent about this but we get away with it by doing root validation in 2 places) we should be OK.

**Comment by cyli** [comment]
@endophage Ok.  I am happy to change that function, and to use it in the server check too (yay same code in both places!) if you don't think there'd be any backwards compatibility issues.  (if the user had some broken repo already that they wouldn't be able to pull or push anymore)

**Comment by endophage** [comment]
@cyli only people that have manually messed with their repo would be in a bad state afaik, and I don't have much pity for them...
