### ISSUE TITLE
Build notary on Windows

### ISSUE THREAD

**Issue by michaKFromParis** [docker/notary#551]

**Comment by friism** [comment]
You should be able to cross-compile to Windows (eg. on CircleCI), all the other projects do that.

@mikedougherty is working on getting Windows CI running on the Jenkins setup: https://github.com/docker/engine-api/pull/136

**Comment by dgageot** [comment]
ping @docker/core-notary-maintainers Is it something we can expect?

**Comment by dmp42** [comment]
bump @docker/core-notary-maintainers :)

**Comment by endophage** [comment]
We should be able to get this working without too much problem if we don't include yubikey support. I don't have a good feel for what it will be like getting yubikey support included on windows.

It's not scheduled in the 0.4.0 timeframe but we can look at it after that release is cut and release a first windows build at 0.4.1.

**Comment by dmp42** [comment]
Thanks @endophage - what would be the approximate release date for 0.4 & 0.4.1 respectively?

**Comment by endophage** [comment]
0.4.0 should get an RC cut sometime around mid-August but is dependent on other releases happening around then. If they are delayed, Notary will be as well.

We don't have a schedule for 0.4.1 yet. It would likely be a release just to add Windows builds.

**Comment by riyazdf** [comment]
been poking around with @endophage, and found some issues that we're now fixing.  Reporting back for tracking purposes and fixing:

- [ ] `notary.NotarySupportedSignals` is not Windows-compatible (`syscall.SIGUSR1` and `syscall.SIGUSR2` do not exist on windows)
- [ ] Generally using `filepath.Join` wherever possible due to `/` vs `\` discrepancies
- [ ] Relative path logic is more complicated (`filepath.IsAbs` checks for drive letters) 
- [ ] Similarly, in tests, `ioutil.TempDir("/tmp", ...)` is not Windows-compatible because Windows does not have a `/tmp`
- [ ] Changelist ordering from the filesystem does not seem to be respected, investigating further

**Comment by endophage** [comment]
As of 0.4.2 we started releasing windows builds.
