### ISSUE TITLE
Compose file should not use notarymysql which has hardcoded passwords

### ISSUE THREAD

**Issue by jfrazelle** [docker/notary#75]
The default suggested deployment shouldn't have the dockercon demo hardcoded stuff, the database should be created by the user then the schema can be initialized by the server itself if it knows it's empty

**Comment by jfrazelle** [comment]
ok my bad it says for development but I do think the password information should rather then be set via env variable in the compose file itself for better visibility

**Comment by RichardScothern** [comment]
Agreed on both points.  Ansible will inject the config paths and passwords from environment variables.  For devel, we could do with a more sensible default than 'dockercondemo' though.

**Comment by endophage** [comment]
Going to close. We've fixed up the user and database names to not be `dockercondemo` any more. @RichardScothern the current docker deployment of notary uses a templating system to read the variables ansible puts in the ENV into a templated configuration file.  We discussed adding that templating in here, I even had a PR for it at one point, but we ultimately decided we didn't want to force that dependency on users.

As we get more and more configuration options, it's impractical to read everything from the ENV because it makes it a pain to tell what is/isn't set and what is required/optional. I don't want to set the precedent that it's OK to cram everything in the ENV. It really doesn't make sense for a server application where the configuration changes very rarely.
