### ISSUE TITLE
snapshot key trust data unavailable.  Has a notary repository been initialized?

### ISSUE THREAD

**Issue by ghost** [docker/notary#762]
I am trying to test the docker content feature with the help of instructions at https://docs.docker.com/engine/security/trust/trust_sandbox/. (When I tried last time , everything worked well) So, I made almost everything work but stumbling upon a new issue now. I ran the container linked with notary server etc. (exactly as per the instructions on the above given link). When I am trying to push the image it is giving me the error of - " 
Error: trust data missing for remote repository sandboxregistry:5000/test/trusttest or remote repository not found: snapshot key trust data unavailable.  Has a notary repository been initialized?" 

My notary server is initialized - Screenshot attached. Can someone help me in solving this issue? 

I did not do any changes in the notary and it is exactly as per the instructions on the website. I saw this post - https://forums.docker.com/t/cant-get-notary-content-trust-delegation-to-work/9029/9 but I still could not resolve it. 

![errrrros](https://cloud.githubusercontent.com/assets/18063453/15729830/8e14d682-281c-11e6-9430-30c718863f41.PNG)

![capture](https://cloud.githubusercontent.com/assets/18063453/15729282/97727950-2817-11e6-895e-257a5ff7ff7c.PNG)

**Comment by mkonakan** [comment]
@cyli Any help appreciated.

**Comment by mkonakan** [comment]
So, looking at this page https://github.com/docker/docker/blob/master/api/client/trust.go 
says that my error might be because of Repositorynotexist, but as you can see my sandboxrepository that  generated basing on the instructions on website is also running and active.

But one thing to note - > whenever I run the repository (private sandbox for testing this docker content trust), it gives be lot of errors on the console I run it (screenshot attached). Container runs but gets some errors like the one in screenshot. Will it have anything to do with this error? 

Is this error because of non proper initialization of notary server or sandboxregistry? 

![errors](https://cloud.githubusercontent.com/assets/18063453/15729803/3cc7cdd4-281c-11e6-9e65-36b66bfb4f17.PNG)

**Comment by riyazdf** [comment]
hi @mkonakan: could you try adding `-D` to your push command (ex: `docker -D push sandboxregistry:...`) so we can see more debug logs?  Also, could you please tell us which version of docker you are pushing with?

**Comment by mkonakan** [comment]
@riyazdf Thanks for the quick response.

Seems issue is with 404 HTTP status? 

![debug logs](https://cloud.githubusercontent.com/assets/18063453/15730813/e2aa1376-2824-11e6-9398-b3d07dfa13b7.PNG)

**Comment by riyazdf** [comment]
Additionally, which version of notary client, server, and signer are you running?

**Comment by cyli** [comment]
It seems to be 404-ing when getting a snapshot key specifically, which is
odd. Just a sanity check myself, is this a fresh (recent) checkout of the
notary server?  Because the new docker automatically uses server snapshot
signing but very old versions of the notary server did not support it.

Could you also please attach the compose logs?  Specifically the server and
signer logs?

**Comment by mkonakan** [comment]
@riyazdf 
Can you help me how I can extract the versions of them? I have done exactly in the same way, it was instructed on this link - https://docs.docker.com/engine/security/trust/trust_sandbox/. 
In the folder where the file was extracted, I can see a filename NOTARY-VERSION with 1.0-rc1 in it. Not sure if its the same version for entire package. 

@cyli As I said, I followed the instructions on above link and it seems to be getting the latest notary from link in this command - "git clone -b trust-sandbox https://github.com/docker/notary.git", also distribution project from link in -"$ git clone https://github.com/docker/distribution.git"

**Comment by cyli** [comment]
@mkonakan oh oops sorry I missed the -b in the instructions.  It's telling
you to check out a really old branch that doesn't support server snapshot
signing.  Can you try the same command without the -b?

That should be getting you the latest version that should support it.

**Comment by mkonakan** [comment]
@cyli  It says fatal:  repository 'trust-sandbox' does not exist when I try it without -b. with -b , it clones.

**Comment by cyli** [comment]
Er sorry, I wasn't clear - I meant without that branch argument entirely.
So "git clone https://github.com/docker/notary.git". :)

**Comment by mkonakan** [comment]
No. your fine. Its my mistake. I never worked with git as I am not a developer. So, do not know it. 

I tried what you said and then now, some other error started popping in - attached 
![new error](https://cloud.githubusercontent.com/assets/18063453/15732583/42161572-2833-11e6-9ab1-69fbb4e5d270.PNG)

**Comment by mkonakan** [comment]
I updated my base machine hosts file based on the container names now. Is there something I am missing? 

Also, I am not sure server and signer containers are getting destroyed frequently. I am not doing any changes to them. Known bug? 
![hosts](https://cloud.githubusercontent.com/assets/18063453/15732707/43eb2b02-2834-11e6-8b0c-e1afa37ee662.PNG)


![hosts file](https://cloud.githubusercontent.com/assets/18063453/15732594/7ec3e6c0-2833-11e6-8180-aff14bf228d4.PNG)

**Comment by cyli** [comment]
@mkonakan Apologies for the slow response, I am still trying to replicate.  The best way to ensure the containers are destroyed are to `docker-compose down` in the directory where you `docker-compose up`'ed.  

You also shouldn't need the container names in your `/etc/hosts` files.  It's weird that it's trying to reach a different IP - I'm not sure what 192.168.200.2 is, although port 53 is the DNS port, so maybe it's trying to do some sort of DNS lookup?  I would expect it to be trying to contact notaryserver at 127.0.0.1, given your hosts file, and certainly not at port 53.

**Comment by mkonakan** [comment]
@cyli that IP is my DNS address and it is doing an DNS lookup for notaryserver address but not sure why it is getting failed. This link - "https://docs.docker.com/engine/security/trust/trust_sandbox/" asks to add details to hosts file , so I did add them. 

I am not sure the necessity for issuing docker-compose down, I said that containers are getting destroyed by themselves when I am issuing that pull command and I am not sure why they are getting destroyed.

**Comment by cyli** [comment]
@mkonakan So I've come across a couple issues so far with the doc:

1.  was the removal of the `-b trust-sandbox` argument from the git-clone command
2.  not sure if you're running into errors like:
     ```
     Warning: failed to get default registry endpoint from daemon (Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)). Using system default: https://index.docker.io/v1/
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
    ```
    if you are currently running an older docker version - if so, we can address that
3.  The command to:  `docker run -it -v /var/run/docker.sock:/var/run/docker.sock --link notary_notaryserver_1:notaryserver --link sandboxregistry:sandboxregistry notarysandbox`  should be changed to `docker run -it -v /var/run/docker.sock:/var/run/docker.sock --link notary_server_1:notaryserver --link sandboxregistry:sandboxregistry notarysandbox`, otherwise it doesn't even work for me.

If you've already addressed these and are still getting the error, please let me know.  I'm still continuing on, but am on very slow hotel wifi, so it's slow going :)

**Comment by mkonakan** [comment]
@cyli 
1. I did make the change 
2. I did face it but then resolved it 
3. I did change it when I changed the -b argument 

Yes, still this issue

**Comment by cyli** [comment]
@mkonakan Hmm... is it possible you've encountered the same issue as https://github.com/docker/notary/pull/753?   What happens if you `docker run -it -v /var/run/docker.sock:/var/run/docker.sock -e GODEBUG=netdns=cgo --link notary_server_1:notaryserver --link sandboxregistry:sandboxregistry notarysandbox`?  (also, after you run, can you do `docker ps`, figure out which container you're running in, and `docker inspect` it to confirm that it's actually linked to the notary server?)

**Comment by mkonakan** [comment]
@cyli
1. Seems this is working , I was able to sign the images with no error now.. I just tested one operation and will do the rest tomorrow and let you know for any other issues. 
2. Also, would request you to update the documents accordingly so that people would not stumble on this like me :) 
3. Finally, thanks a ton for your support even staying in hotel :D 

I will go through the analysis of why this issue occurred and what solved it tomorrow and let you know for any other questions. Thanks again man :)

**Comment by cyli** [comment]
@mkonakan Thanks lots for trying content trust, and reporting these issues with the docs!  Will definitely make that update.  :)

**Comment by mkonakan** [comment]
@cyli I was just checking through this again. In later steps, there are also many things to be changed so that it would not confuse the people who are trying this. 

1. Seems the sandbox registry image is built based on GOLANG base image, so docker exec -it sandboxregistry would give us an error and we need to change that to "docker exec -it sandboxregistry /bin/sh" 

2. Error messages - All the error messages current link seems to be of old version. It displays a meaningful statement now instead of "no trust available etc" and also displays "manifest unknown" instead of "filesystem verification failed... etc". 

Making these changes should be helpful for people who are trying to work with this latest version of docker content trust.

**Comment by cyli** [comment]
@mkonakan Thank you for all the suggestions!  I will add those to the change.

**Comment by mkonakan** [comment]
@cyli I was also wondering the necessity for step 7 in "testing malicious images" in that section. I do not think it is needed there as we can check even without that that verification was failed. Is there anything I am missing?

**Comment by cyli** [comment]
@mkonakan It's to prove that it will not download the image, and it will not be there when you do `docker images`.

**Comment by cyli** [comment]
@mkonakan Out of curiosity, do you have more than 2 DNS servers configured on the host?  (I am trying to figure out why the `GODEBUG=netdns=cgo` thing worked for you - I haven't been able to replicate that particular failure).

**Comment by mkonakan** [comment]
@cyli Haha, I was actually thinking the reason for docker rmi in other angles...Dint think too simple :P

I do have only one DNS server. In my opinion the reason for error being that the Go resolver not looking at hosts file to figure out the address of notaryserver from hosts file and trying to resolve on its own... I did not dig on it too much after this reasoning.

**Comment by innocentme1** [comment]
@cyli Did you do any changes to the tutorial on website? I have done the changes mentioned above, it worked pretty well for sometime and then it started giving me errors like attached. Also, the server and signer containers are getting killed automatically - not sure why. In between the docker ps commands in screenshot I made a compose up command to bring the containers. Kindly help! 

![upload](https://cloud.githubusercontent.com/assets/19864555/16029387/6892bae8-319d-11e6-8956-fc22b84236e5.PNG)

**Comment by cyli** [comment]
@innocentme1  No, no change to https://docs.docker.com/engine/security/trust/trust_sandbox/

https://github.com/docker/docker/pull/23195 was just merged today, if that's what you're referring to, but that change is not reflected at https://docs.docker.com/engine/security/trust/trust_sandbox/ yet.

If you are following the old instructions, everything should still work as before.  I'm not sure what's causing the new network issues.  :|  

Could you try giving the new instructions a shot, and see if that helps?

**Comment by innocentme1** [comment]
@cyli it shows no route to host when containers are dead (as expected) and connection refused when container is up.

**Comment by cyli** [comment]
Are containers continuing to kill themselves with the new
instructions too?  Could you try removing all existing containers first?

**Comment by innocentme1** [comment]
not yet tried new instructions. will try them and let you know 2mrw morning. Are you referring to the instructions at - https://github.com/docker/docker/pull/23195/files?

**Comment by cyli** [comment]
Yep!  Although removing the trust sandbox container first may be a good
idea if you haven't tried that already.  If notary server goes down and you
bring it back up, trust sandbox may not be correctly linked afterward.

**Comment by innocentme1** [comment]
I tried that already. Lets see with new instructions.

**Comment by cyli** [comment]
@innocentme1 

If you have time, no particular hurry, what happens if you run the following in two different terminals?

1. `docker run --rm -i --name testserver alpine nc -l -p 4444` in one terminal
2. `docker run --rm -i --link testserver alpine sh -c "echo hello | nc testserver 4444"`

I see "hello" in the server terminal, but I'm wondering if you get a network error like `nc: bad address 'testserver'`.

**Comment by innocentme1** [comment]
@cyli nope. no error. it works fine for me too!  It seems to be some error in dns resolution or error with server image/compose file that was provided. I will try to troubleshoot it for sometime tomorrow else will run the new instructions. What I wondered is - it worked for sometime and all of a sudden, it started not to work. I did some testing on artifactory but I think that would not have tampered anything of my current DCT setup. Issues in DCT setup is really killing so much time :(

**Comment by cyli** [comment]
@innocentme1 Out of curiosity, are you using docker-machine or running this all on your local machine?

**Comment by innocentme1** [comment]
@cyli local machine based on Ubuntu.

**Comment by cyli** [comment]
:|  Ok, then I have no clue.  There can be an issue if you are running this against a docker machine, since the notary compose file mounts volumes containing the mysql init - and if that volume isn't mounted, then notary server and notary signer can't connect to the mysql instance because the users were never created.

But should work fine if it's all local.  Sorry, I have no idea what is causing the DNS issues.  The new compose file shouldn't require any local volumes or `/etc/hosts` hacking, so hopefully that may work better.

One last thing, if you hadn't tried it previously - maybe deleting the notary mysql volume in addition to the containers (possibly with `docker-compose down -v`) before running `docker-compose up`?  Otherwise I'm out of ideas, apologies.

**Comment by innocentme1** [comment]
@cyli Its not actually DNS issues, its more to networking issues. If you see it says : connection refused and then immediately containers get killed after this message. I tried the last option u said - it dint work. So, I am only left with working on new instructions then.

**Comment by cyli** [comment]
@innocentme1 The connection refused makes sense - the server and signer aren't running within the containers, if the connection is getting confused and the containers stop running.  The question is why they're not running - if you could run `docker-compose logs` in the notary repo, that might give us a little more info.

It's possible there's a DNS or other connection between the server/signer and the mysql instance - which is why I asked whether you were using docker-machine.

**Comment by innocentme1** [comment]
@cyli Thanks for assisting me continously everytime and anytime really quick:)  Thank you so much. 

Alright. Nooo. You got me wrong. this connection refused occurs "even" when the containers are up and running. I verified this with ps but soon after this refuse error message , server and signer containers get killed. I am not sure if ur looking for attached screenshot logs, I did run the command within the notary folder on my base machine. 

Surprising message to me "waiting for notarymysql to come up" - is this why the connection refused error? but I have the mariadb image up and running during this message..Is there something I am missing here? 

![compose-logs](https://cloud.githubusercontent.com/assets/19864555/16062958/75d6a0bc-324b-11e6-8deb-5d81dfb625a4.PNG)

**Comment by innocentme1** [comment]
Also, I will keep parallely trying the new instructions set.

**Comment by cyli** [comment]
@innocentme1 No problem, I am very curious to figure out what's wrong.

Sorry, I didn't explain myself very clearly - "waiting for notarymysql to come up" is what I was expecting.  The container is running because the startup script inside the container polls the mysql server for about 30-35 seconds, so during that entire time, the container itself is running running.  When the startup script fails to connect for the last time, it exists, cause the container to stop running.

In the meantime, although the container is running, the server is not running - the startup script waits for a connection to mysql before actually starting making a call to the server binary to start.  That's why you are getting a connection refused message rather than a no route to host message.

Could you modify `migrations/migrate.sh`, line 11 thereabouts, to read:
```
		until migrate -path=migrations/server/mysql -url="mysql://server@tcp(mysql:3306)/notaryserver" version
```
(get rid of the pipe to `/dev/null`) and try again?  This should let us know why the server is failing to connect to mysql.

**Comment by innocentme1** [comment]
Yup I removed the /dev/null in that 11th line, destroyed the containers and then docker-compose up'ed them again. and this time logs are like attached. I could not figure out something great in this except "database was not shutdown normally" and the log prior to it. 

![helll](https://cloud.githubusercontent.com/assets/19864555/16063483/7934e4e6-324e-11e6-8cbe-062d64f490bd.PNG)

**Comment by cyli** [comment]
@innocentme1 Could you find the notary_server logs?  The mysql logs won't necessarily tell us why notary server is refusing to connect :)

**Comment by innocentme1** [comment]
@cyli 

hmm. As I said before, attached are the logs I can see ...saying waiting to come up and nothing else. 
![logs](https://cloud.githubusercontent.com/assets/19864555/16063987/3d74df66-3252-11e6-81d3-44c2e0d9c4c4.PNG)

Am I missing something that u require?

**Comment by cyli** [comment]
@innocentme1 By removing the pipe to `/dev/null`, the notary_server container should print out why it's failing to connect to the mysql container, as opposed to just the "waiting for notarymysql to come up" message (which only lets us know that something went wrong, but not what).

You may have to rebuild (`docker-compose build`) before running `docker-compose up` again.

**Comment by innocentme1** [comment]
I did rebuild - let me give a try and let u know. 

@cyli I am also parallelly trying the new instructions (Yeah, I have to make this setup live ASAP as its highly critical for us here) and It gives me the following error. I am running compose version 1.7.1 which crosses the minimum requirement mentioned by u the instructions. 

error:
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.volumes: 'notarycerts'
Unsupported config option for services.networks: 'sandbox'

**Comment by cyli** [comment]
@innocentme1 There should not be any indentation in front of your "volumes" and "networks" declaration -  they should be on the same indentation level as services, which should be none.

**Comment by cyli** [comment]
@innocentme1 

> Yeah, I have to make this setup live ASAP as its highly critical for us here

Just to be clear, also, the new instructions are for sandbox testing - if you want to get a live signing server up, you probably want a real DB with persistent data.  In which case, you probably still want the compose file in the notary repo.

**Comment by innocentme1** [comment]
@cyli I rebuilt again and now below are the logs. This seems to be opening tcp on 10.5.74.105 on 3306. this IP is internal virtual IP seems to be load balancer. I am not sure why it is dialing to it on 3306 ( 3306 is port we opened for  mysql? ) 

dial tcp 10.5.74.105:3306: getsockopt: connection refused
waiting for notarymysql to come up.
dial tcp 10.5.74.105:3306: getsockopt: connection refused
waiting for notarymysql to come up.

Also, yeah I knew that they are for sandbox testing. I am currently evaluating docker content trust itself and I am supposed to provide my report in 2-3 days time after which we might end up using this in our docker environment where we will set up our own notary.

**Comment by cyli** [comment]
@innocentme1 Yep, 3306 is indeed the mysql port.  So if you do `ping mysql` on your local machine, outside of any containers, it hits 10.5.74.105?

**Comment by innocentme1** [comment]
@cyli Ahhh....yes...!

**Comment by cyli** [comment]
:|  You're hitting the same weird DNS bug as https://github.com/docker/notary/pull/753.  Which I've been asking around about, but no one else seems to be able to replicate (let me see if I can come up with a very simple test case that fails in the same way).

In the meantime though, I think you might have to add the `-GODEBUG=netdns=cgo` environment variables to the compose file as per https://github.com/docker/notary/pull/753/files#diff-8857124ebdcf7d878ada27a8dd023ea4R10.

**Comment by innocentme1** [comment]
@cyli
 
1. I am happy that you got someone to replicate your debug issue :P and I am sad that it was me :| 
2. I tried the new setup instructions - working perfectly. Man, working with the old and new instructions , I can say that this new ones are way simple and better than the old ones. Also, I am not sure if its the case with you too- I found the signing , push and pull mechanism to be "very slow" in this new setup trustsandbox container 
3. We encountered this last time but when I added this -GODEBUG=netdns=cgo with -e flag while running / launching container , it was solved (Remember? the one we debugged in starting of this thread - I am the ghost , had to del my old account for some reasons). Let me try to add this to compose file and try it and will let you know.

**Comment by cyli** [comment]
@innocentme1 

> I found the signing , push and pull mechanism to be "very slow" in this new setup trustsandbox container

I didn't notice much of a difference in my setup, but since docker-in-docker writes images to a docker volume, it might depend on your volume driver.

> We encountered this last time but when I added this -GODEBUG=netdns=cgo with -e flag while running / launching container , it was solved

Yep, I remember - is the mysql address on your network new?  Not sure why it worked before and just started failing recently.

> Can you quickly reflect the changes on the website so that people need not struggle

I'm not sure when the next doc build for docker/docker is - I can submit a PR to the existing docs, but I'm not sure when they're rebuilt.

I would also like to track down the `GODEBUG` issue a little bit before listing it as a workaround, since I don't really know how to describing the exact case in which it might be a fix.  Unfortunately I'm completely out of my depth here with regards to the networking.  If you wouldn't mind - I apologize for the trouble - but if you hit the exact DNS issue with trying:

1. `docker run --rm -i --name mysql alpine nc -l -p 4444` in one terminal
2. `docker run --rm -i --link mysql alpine sh -c "echo hello | nc mysql 4444"` in another terminal?

could you file a bug with docker/docker with your exact docker client/server details and ubuntu setup?  They might have better ideas about what questions to ask to figure out what's causing this.

**Comment by innocentme1** [comment]
@cyli 

I am not sure about that address being added newly. I tried this last night at home too but still same issue. 

Sure. I will do verify that and file to docker/docker sometime this weekend? I have some important tasks to work on as the setup is up and running now.

 Also, I did do the changes in the compose files and rebuilt them. It works perfectly now :)  so adding this GODEBUG to run command is not helping but adding it in compose file and making changes is working good.

**Comment by cyli** [comment]
@innocentme1 Whenever you have free time, thanks so much for your patience and perserverance .  :)

**Comment by innocentme1** [comment]
@cyli thanks. 

1. In case, we need to check test the rotating keys option in this test setup we made, how do we do that? I am little confused with the notary client CLI thing described here : https://docs.docker.com/notary/advanced_usage/ . In our setup, sandbox (I am still running with old instructions set) is the client which will be having keys and pulls metadata from notary server right? So, do I need to rotate keys on this and they will be synced with notary server? 

P.S: This TUF and entire Notary architecture is kind of really taking quite some time to understand. Any specific resource you would suggest for me to take a look at for in-depth understanding of moving this Notary to production environment and also rotating keys etc. 

2. When moving to production, we need to change the server , signer, and root ca certificates in /fixtures folder, thats it "w.r.t to certificates" right?

**Comment by endophage** [comment]
@innocentme1 the [TUF specification](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt) is a good place to start to understand how Notary is attempting to do things. There are some nitty gritty implementation differences and we currently only support a non-configurable threshold of 1. We've also implemented a custom prioritization for traversing delegations (which the spec specifically leaves open for users to do) in docker, but the notary CLI will do a pre-order depth first search of the delegation tree for a given target.

You are correct that you just need to replace the keys and certs in /fixtures.

**Comment by innocentme1** [comment]
@endophage: I did go through it and took quite some time to understand everything. It is fine in my head now but the way Docker implemented it via Notary is little confusing to me now. I will try to figure that out. 

Also. I am yet to research the delegations part. Thats on my next to-do list. Your reply answered my second question but not the first one. Can you throw some light on it too?

**Comment by endophage** [comment]
I'll do my best to answer your key rotation question.

The client and server do not syncronize keys. The client holds some private keys (always root and targets, sometimes snapshot) and the server holds the others (always timestamp, sometimes snapshot). Currently we only support the rotation of keys held by the client (we have started work on rotating keys held by the server), and the transfer of snapshot signing responsibility between the server and client (if the client owns the snapshot key it can be rotated, if the server owns the snapshot key, currently it cannot be rotated).

When you rotate a key held on the client, a new keypair is generated, the existing public key is removed from the appropriate role in root.json, and the newly generated public key is assigned to that role in root.json.

If it is the special case of the root key being rotated, the old root role is saved in root.json as `root.<version>` where `<version>` is the version number of root.json indicating the last version for which that root role was valid. The old public root key is also kept in the keys map in the root.json. This information is _only_ used as a hint to publishers which old root keys need to be used to sign a root.json. It is not used by consumers at all.

**Comment by innocentme1** [comment]
@endophage sounds good as of now. Will let u know as I move on. 

Also, Incase if I am using docker hub instead of registries for storing my signed images. do I need to add any env variable like "export DOCKER_CONTENT_TRUST_SERVER=https://notaryserver:4443" which we do for registries? I tried without and with giving "notary.docker.io" but it gives me an error like "Error establishing connection to notary repository: failed to create private key store in directory:"  Am I missing something?

**Comment by endophage** [comment]
If you are using the `docker` CLI you need to provide `DOCKER_CONTENT_TRUST_SERVER`. If you are using the `notary` CLI you should provide the same server URL as the `-s` flag. Alternatively, if you only interact with one server (or at least, with one server much more than others), you can use a notary config file: https://docs.docker.com/notary/reference/client-config/

**Comment by endophage** [comment]
That looks more like there's a permissions problem with your ~/.docker directory. Could you post the output of `ls -la ~ | grep docker` and `ls -la ~/.docker/`.

**Comment by innocentme1** [comment]
It is indeed a permission issue. Rectified. Sorry. What confused me is the statement : "Error establishing connection to notary repository" before the failed to create..... Why would it fail establishing connection because of permissions? :/ I think little more clear statement should be good.

**Comment by endophage** [comment]
Yeah, I think that `Error establishing connection` prefix comes from Docker rather than Notary. Still our job to fix it but if memory serves it was phrased that way because almost all the errors Notary returns up to Docker are network related.

**Comment by innocentme1** [comment]
@endophage @cyli  

hmm. I am little confused on rotating keys part. I just pushed a signed repository to my docker hub and then I am trying to rotate the keys. The command "notary key list" says - " no signing keys found"  even I have all the keys in my ./docker/trust....folder. Reference attached. Only if I am able to list them, I can get the GUN and then rotate them right? 

![no keys](https://cloud.githubusercontent.com/assets/19864555/16103026/bf79069a-3329-11e6-8725-0beda591a8ac.PNG)

**Comment by endophage** [comment]
Try `notary -d ~/.docker/trust key list`

Notary is an independent project from Docker and by default puts all data in the ~/.notary directory. It's necessary to point it at the ~/.docker/trust directory to see docker related trust data.

**Comment by innocentme1** [comment]
@endophage  Sorry for delayed response and thanks for helping me all the time. 

1. When I rotate the keys , it gives me the error as "*fatal : client is offline". I tried to check if Internet is reachable - infact , it is!  Not sure what else does this error mean? Anything else to be done from my side? 

This also means that the key is not rotated because I tested it as below
          a. Rotated the targets key 
          b. Pushed to my docker hub account with old and new keys still present on my machine: Push       was successful 
          c. Removed the old key, kept the newly rotated key and then pushed it again:  it was failure. I also pushed it with debug mode which indicated that it is looking for old targets key. Though the new one is created, it is not being looked for as it seems not to be synced with docker notary (client offline error). 

notary -d ~/.docker/trust/ key rotate docker.io/mkonakan/wordpress targets --server-managed=false
Enter passphrase for new targets key with ID 0b9e7c7 (docker.io/mkonakan/wordpress): 
Repeat passphrase for new targets key with ID 0b9e7c7 (docker.io/mkonakan/wordpress): 

*** fatal: client is offline**


2. Is there any documentation that is made for rotating keys etc.operations on Notary CLI? I could not actually find. I only found brief intro to it on "advanced users guide for notary cli etc. page"  I am feeling strange about how to know where abouts of using entire CLI in production environment. Documentation on Docker website regarding this particular one seems little confusing and not in proper formatted as it is done for other documentations. Is it that I still need to spend some time to get dig through it or else is the documentation still not full-fledged? 

3. Do you think entire DCT is production ready?

**Comment by cyli** [comment]
@innocentme1 Can you try running the notary command with a `-D` to get debug output?   `notary -D -d ~/.docker/trust ...`

**Comment by innocentme1** [comment]
@cyli Hey, below are messages of our interest 

ERRO[0000] could not reach https://notary-server:4443: Get https://notary-server:4443/v2/: dial tcp: lookup notary-server on 127.0.1.1:53: no such host 
INFO[0000] continuing in offline mode           

Surprised. Do I need to change this host address somewer? add some config file or something?

**Comment by cyli** [comment]
@innocentme1 Are you using the trustsandbox setup?  (e.g. are you executing the notary commands from within the trustsandbox container?  If so, I think we linked that one as notaryserver, not notary-server.

**Comment by innocentme1** [comment]
@cyli figured out the issue. Thanks! 

I am running on my base machine and I passed the trust server address with -s flag and it works fine now!
