### ISSUE TITLE
Update the auth permissions so that delete repo requires admin permission

### ISSUE THREAD

**Issue by cyli** [docker/notary#789]
I think that means all permissions (`*`), not just push/pull.

Confirmation from @jlhawn that `scope=repository:library/foobar:*` is given only to namespace admins, as opposed to anyone with read-write access.

**Comment by riyazdf** [comment]
I've been investigating this a little bit further -- this shouldn't be too much work on the delete side, but will require some changes on publishing.

Since we currently don't separate an initial publish vs. subsequent publishes, we'll have to check on the server if we have any trust data and send a new challenge for a token with admin (`*`) permission if this publish is initializing trust data for this repo.

**Comment by riyazdf** [comment]
After digging around more, I'm currently of the opinion that the initial push should remain as is (requiring `"push"` and `"pull"`) rather than `*`.  Changing the required permissions would impose a hard break on old clients since they would not be able to form correct transports.

**Comment by endophage** [comment]
Closed by #819
