### ISSUE TITLE
Document deviations from TUF

### ISSUE THREAD

**Issue by KellerFuchs** [docker/notary#794]
The [service architecture doc](https://github.com/docker/notary/blob/master/docs/service_architecture.md) starts by stating that Notary implements The Update Framework.

Please document the deviations from the TUF spec, their rationale and an argument for it not compromising the security of the system, including:

- the repository and targets are conflated (there is only one target per repository);
- by default, a root key is silently generated alongside a target key, and stored on the local computer.

**Comment by riyazdf** [comment]
Hi @KellerFuchs, can you please explain where the deviations are from the [TUF spec](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt)?  From my understanding, these are implementation details outside of the realm of the TUF spec, and as such do not deviate or violate the specification itself.

**Comment by cyli** [comment]
@KellerFuchs Also, could you elaborate on "one target per repository"?  Unfortunately the word "target" itself is somewhat overloaded in the spec.

Do you mean one targets file per TUF repository?  I believe that according to the [0.9 spec](https://github.com/theupdateframework/tuf/blob/1bed3e09a478c2c918ffbff10b9118f6e52ee129/docs/tuf-spec.txt), there is only one top level targets metadata file, and there can be many delegation metadata files, all of which are also type "Targets", but only the top level one is called `targets.json`.

Or are you referring to how Docker Content Trust sets up one TUF repository per image namespace - e.g. one TUF repo for `docker.io/library/alpine` or one for `docker.io/library/ubuntu`?  This is definitely different from the two TUF proposals for Python ([PEP458](https://www.python.org/dev/peps/pep-0458/) and [PEP480](https://www.python.org/dev/peps/pep-0480/)), although a docker image namespace might have many images, each one corresponding to a tag, such as "latest" or "16.04" or "xenial" in the case of ubuntu.

**Comment by KellerFuchs** [comment]
@cyli Yes, I was talking of the repository scoping.
It's true that the spec is not completely clear, actually: it did go against my understanding of the spec, but a second careful reading made it apparent that this point is not in itself a deviation.

This is an issue from a security and manageability perspective:
- From a security perspective, having the repository scoped to, say, [`hub.docker.com/r/hashbang/`](https://hub.docker.com/r/hashbang/) or to specific images there make a big difference:
  - with per-org scoping, an attacker gets one single opportunity to serve a compromised image, either because the client used TOFU or because they confused the user in accepting their root key(s);
  - with per-image scoping, an attacker gets this opportunity any time a new image is fetched (for the first time).
- From a manageability perspective, eliminating those concerns by deploying once a root key pin (using whichever configuration management system) for the whole organization is easy, whereas doing so every time a new image is created is hard/tedious.

I gave the examples for Dockerhub, but as you made clear with the library example, there are other users of Notary.
- For `docker.io/library`, I would argue that the right scope is the entire library:
  - it makes trust manageable: the client only needs to ship with the library's root key baked in;
  - it makes key loss/repudiation more recoverable: in the worst case, should the maintainers of one image lose the ability to sign it, they only need to re-establish trust with the operators of the library out-of-band, and the root can issue a new delegation; in the other case, it's simply impossible to recover safely without end-user intervention.
- For other users (with a potentially custom hierarchy), I think the most reasonable thing would be to allow them to define what the scopes should be.

However, we established at the beginning that it's not, in itself, a TUF deviation.
Should I move all of this to a different issue?

**Comment by KellerFuchs** [comment]
@riyazdf It specifies that the root keys [“should be kept offline.”](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L243-L244).

Notary's default is not this, the documentation mentions nothing about this, and it doesn't seem possible or supported to generate and store the root key on an offline (“airgapped”) system (without moving it online every time the root needs to sign metadata).

**Comment by endophage** [comment]
Hi @KellerFuchs, apologies if our responses are slow over the next few weeks. We're all on deck for DockerCon. Regarding some of your comments about scoping of repositories:

  - It would require much more complex logic to deal with multiple images in the same TUF repository all using the same tags (i.e. `latest`, `1.0`, etc...). We would have to do a _lot_ of custom handling of delegated roles or namespaced tag names (which we would then have the trim for display). 
  - The trust pinning work aims to do away with TOFU for those that require a high security environment. It's merged into Notary and will be coming to Docker in the not too distant future.
  - Allowing users to choose their level of scoping is already possible by choosing which root key they use to initialize a new repository. We've discussed allowing trust pinning to specify a root key (not just a CA bundle) for a glob, so we would be able to specify all of `docker.io/library/*` used the same root key. However I believe at the organizational level, using a CA will make more sense for the reason presented in the immediately next point.
  - Organizations may have a single presence on hub but many sub teams that do not share keys. The design does not prevent them from requiring all teams use the same root key and have to come to a centralized holder to initialize their repo, but the design also does not require it. Whether the root key used is the correct one can be gated at deployment time (because it's also annoying and bad practice to prevent people from pushing if they don't have the right key, users should always be able to backup by pushing _somewhere_).
  - It's involved, but airgapped networks are entirely possible with no need to bring the root key online. We could definitely make improvements here and are open to suggestions as this is a use case we want to support. It simply hasn't been a highly requested feature so far. We also introduced Yubikey support for root keys so that bring the key online could be a safe operation (it always requires touch and you can configure a pin code that must be entered to perform signing).

We have no plans to support custom hierarchies. As you've already found out, the TUF spec is complex and nuanced. I believe hierarchies as I understand how you are describing them are not what the TUF spec was designed for. There should not be multiple instances of the same target name in a single TUF repo, all of which are equally valid depending on some specific context (in this case, the context would be the image). While that's not technically in direct contradiction to the spec as it leaves delegation priorities up to the implementer, we wrestled with that concept for a long time and couldn't present it in a way that was understandable to anyone that didn't have a deep knowledge of TUF.

We've talked to the TUF team along the way and any implementation details in which we do deviate have been discussed with them. Some of them will be reflected in the next version of the spec.

**Comment by cyli** [comment]
@KellerFuchs Another reason we do not support organization level repositories is that some organizations have a mix of public and private repositories, and there's no good way to hide those private repositories from public ones if they all live in a single repository.  We can prevent a user from being able to download the delegation targets files for the private repositories, but those files will be checksummed in the snapshot, and can leak information about a private repository's delegation structure and the amount of data within them.

**Comment by KellerFuchs** [comment]
@cyli Very fair point.
Would it work to have separate metadata files for private and public images?

@endophage In order:

1. I don't understand the problem (OTOH, I don't know the internals of Notary, so that might be a naive comment).
Wouldn't you end up with delegations to, say, `debian` and `docker`, who themselves do delegations to `debian/stable`, `debian/7.11`, `docker/1.10` and so on?
2. Part of my point was that, even with trust pinning, having to create new pins any time my organization publishes a new image (and deploy that config change everywhere) is a huge hassle, esp. given that I need to properly check that I know the right root keys, every time (i.e., per-image repositories push the burden of key/trust management on the end user).
3. OK, I wasn't aware of that.  Is it documented somewhere, and what happens if a different TUF repo with a more narrow scope gets published too? 
4. Aren't independent teams perfectly covered by the delegation mechanism?
5. Yes, @lrvick pointed me to the relevant documentations regarding airgaps.
  I might submit PRs to improve the doc, and sorry for not noticing it is actually supported.

Regarding response time, don't worry at all: I have a day job, so it's not as if I'm going to reply instantaneously either.

**Comment by cyli** [comment]
@KellerFuchs:  
 
> Would it work to have separate metadata files for private and public images?

This makes name resolution more complicated because the same repository could exist in both, and name resolution would involve extra logic:

1. We could first check the registry to see if the repository exists, and whether it's a public and private repository, and only then can we determine which TUF repository to pull to do name resolution: the public one or the private one.
2.  We could have a special multi-repository object that enforces that a GUN is unique across multiple TUF repositories.

Both of which would be [outside the TUF spec](https://github.com/theupdateframework/tuf/blob/1bed3e09a478c2c918ffbff10b9118f6e52ee129/docs/tuf-spec.txt#L328) and that more intricately ties Notary's TUF operations with Docker-specific use cases.

---

> Part of my point was that, even with trust pinning, having to create new pins any time my organization publishes a new image (and deploy that config change everywhere) is a huge hassle, esp. given that I need to properly check that I know the right root keys, every time: per-image repositories push the burden of key/trust management on the end user.

You pin a new key for every new repository - we currently support pinning a single CA per repository name prefix - if you use the CA to sign all generate all your org's root keys, and in that case you'd only have to pin the CA.  There is some more work to get that part usable, namely allowing the import of root keys when initializing a repository (see https://github.com/docker/notary/pull/624#issuecomment-226648461).

**Comment by cyli** [comment]
^ sorry, missed a few key words in that comment, namely "don't necessarily" :)  updated.

**Comment by KellerFuchs** [comment]
@cyli Yes, but using a CA in that way breaks some of the security property that TUF brings. For instance:
- having a separate pinned CA [makes rollover hard](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L165-L166);
- having a pinned CA makes the whole infrastructure vulnerable to a [single-key compromise](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L93-L99).

By the way, using a CA [is a deviation from the TUF spec](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L171-L172).

As such, my initial point still stands:
- Notary adds external concepts/PKI/... that ties into TUF implementation: this must be documented along with why it doesn't break TUF's security guarantees.
- This is a direct consequence of having image-level scopes for the TUF repos.
- As @cyli pointed out, supporting private metadata might require some extra work. 
I would point out that bringing the current design to a level of security in line with what TUF does also would require lots of work (and might be even less reuseable).

**Comment by endophage** [comment]
@KellerFuchs none of the problems you present arise from image scoped TUF repos. At the highest level, the widest scope we would reasonably be able to implement, while still maintaining user ownership of keys, as you yourself suggested, is user/org scope.

However, we have new users signing up all the time and new orgs being created. It is impossible for us to ship all their keys ahead of time, presenting the same problems you have been associating with image scope repos because the keys literally haven't been created yet.

CAs are an accepted and widely used form of PKI. They're not perfect, we acknowledge there are many known issues, political and technical, but to be clear, we don't force anyone to use them as the mechanism for bootstrapping trust in Notary. It's entirely acceptable to pin root keys only while disabling TOFU, getting you to exactly the form of bootstrapping presented in the TUF spec.

Frankly, even in the TUF spec, you're typically relying on a CA and TLS to deliver your initial client download to you securely with a pinned root (unless you happen to be delivering clients and keys by hand on physical media). On that basis, using a CA to securely deliver additional root keys seems entirely within the TUF security model, if not explicitly documented in the spec (and if you are delivering keys by hand, you can disable TOFU and install/pin them manually).

As it seems interesting to you and others, we'll put together some more documentation but we have no intention of changing this facet of the implementation.

**Comment by KellerFuchs** [comment]
@endophage OK, we seem not to be understanding one another there.

> At the highest level, the widest scope we would reasonably be able to implement, while still maintaining user ownership of keys, as you yourself suggested, is user/org scope.

Definitely

> However, we have new users signing up all the time and new orgs being created. It is impossible for us to ship all their keys ahead of time

I never suggested shipping user's keys with notary or Docker, if that's what you mean there.
What I said is that, as a notary user, I would want a mechanism to pin trust for my entire org (because, as stated, pinning on a per-image bases is just a nightmare).

> CAs are an accepted and widely used form of PKI. They're not perfect, we acknowledge there are many known issues, political and technical, but to be clear, we don't force anyone to use them as the mechanism for bootstrapping trust in Notary.

Sorry, but I'm not seeing the relevance of that part:
- I do not wish to delve into the political (and I could run my own org-specific CA, which I can't imagine being a “political” issue).
- I never claimed you force anybody to use CAs.
- You are not addressing any of the issues I pointed out regarding the mismatch between using a CA and TUF, regarding manageability and security.  Most importantly:
  - the ability to survive the compromise of any single key is lost;
  - there is no mechanism in place for a CA key rollover.

> you're typically relying on a CA and TLS to deliver your initial client download to you securely with a pinned root

In the use-case I exposed, I don't rely on this at all:

- Docker is installed through distro packages, which implement their own integrity mechanisms.
- Trust anchors are provisioned using whichever configuration management tool I use, likely over SSH.

Regarding your claim that “none of the problems you present arise from image scoped TUF repos”, I will lay it down plainly:
- image-scoped TUF repos mean that (TUF root) pins are scoped to a single image;
- managing N trust pins being a nightmare, this means you add an external PKI to derive trust from;
  (regardless of your feelings on that matter, [it is a deviation form the TUF spec](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L171-L172) because it invalidates the security analysis)
- furthermore, the external PKI provides none of the security guarantees of TUF:
  - it is impossible to survive the compromise of any single key;
  - it has no support for safe key rollover.

> we have no intention of changing this facet of the implementation

Then state clearly that you use TUF but do not provide any of its security guarantees.
It will not make your software secure, but it will save other people lots of energy and effort trying to understand your security model (and getting and EWONTFIX after sinking loads of time and energy trying to fix it).

**Comment by KellerFuchs** [comment]
As an aside, I would be interested to know @hellais' or @vladimir-v-diaz's opinion on this, since you seem pretty determined not to have a security analysis on your own.

**Comment by endophage** [comment]
Apologies if we seem intransigent. There are pieces of the TUF spec you are passing over. Mainly, prior to the part you link:

> "We are not providing a means to bootstrap security so that arbitrary installation of new software is secure.  In practice this means that people still need to use other means to verify the integrity and authenticity of files they download manually." (found in [Non-Goals](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L70))

We fully implement the guarantees of the TUF spec and have simply added a mechanism for bootstrapping trust, something that the spec explicitly notes it does not define.

We would be interested in having a conversation with @vladimir-v-diaz and the rest of the TUF team, who we've communicated with on a number occasions, about bootstrapping, but our inferred understanding of the statement on PKI (we have not confirmed), is that it reduces variables for the purposes of their specification, and its validation. In a practicality, as implementation time, it is necessary to rely on systems outside of the TUF spec to bootstrap. Short of physical hand over of data, this is bound to rely on some form of PKI to provide any security guarantees.

**Comment by KellerFuchs** [comment]
@endophage It's really hard to be having a conversation with you about this when you seem to silently disregard part of what is said.

“bootstraping” and “files they download manually” are one-off operations (hence why the root is *Trust On First Use*).
It is, for instance, setting up docker/notary for the first time on a given host.
It is **not** *Trust On Every Use* (of Docker to fetch a new image).

**Comment by endophage** [comment]
I'm not sure what you feel I'm silently disregarding, but it's possible our differing starting points are making me oblivious to context you don't have. 

It would be useful to separate the problems you're describing because I feel like you're conflating 2 different things. 

First, lets try and put the CA piece to bed, in the general context of notary, independent of the scope of any repository. The CA is _only_ used for bootstrapping, to provide something better that completely arbitrary TOFU. Once you have a root.json you then trust that root.json for ongoing trust over the repo, not the CA.

Separately you disagree with the scope we've applied to repositories specifically in the context of Docker Content Trust. My previous statement still stands, user/org scope TUF repos present a lot of additional complexity that, we believe, would be in direct contradiction to the spec, vs the bootstrapping code which fills a gap the spec explicitly states it does not cover.

To answer why we feel it's in direct contradiction to the spec, I'l try to better describe the situation we discussed earlier with conflicting targets names. 
  - First, because I think you may have some confusion here based on one of your earlier comments: delegation names and target names are mutually exclusive sets. A delegation named "debian" and a target named "debian" have no implicit or explicit relationship under TUF. 
  - At a user/org level scope, many images are currently published. Let's make the (reasonable) assumption that they all publish a tag "latest". Within our user/org scope repo there would necessarily be multiple "latest" tags, one for each distinct image.
  - Our understanding of the TUF spec is that all users should have a consistent view of the repository, therefore, all users should get the same response when querying the "latest" tag in the same version of the TUF repo.
  - You suggestion would require that based on some kind of additional business logic folded into Notary, we would present different views of the repo based on the user's input. Depending on what image we were querying, we would have to find a different "latest" tag.
  - This suggestion presents much greater complexity, and deviates from what we understand the TUF spec to be aiming for.

**Comment by KellerFuchs** [comment]
> I'm not sure what you feel I'm silently disregarding, but it's possible our differing starting points are making me oblivious to context you don't have. 

You implicitly and systematically assume that we are looking at the lifecycle of a single image.
That's exemplified in what you say about TOFU and manual downloads.

Yet, it is a complete disconnect from both the reality of production systems and the TUF spec:

- If I install a new package (say, `apt install nginx`), I'm not creating a new vulnerability window because I can't trust the package yet.  Why would anyone expect (or want) to have this problem while fetching `library/nginx` for the first time?
- The TUF says that initial, manual downloads are not protected.  For our purpose, that's the initial download of a Notary-enabled application: downloading a new image is definitely not a manual operation, since it *is* done through Docker (or whichever else Notary-enabled application).

Given that you have yet to address any of my concerns about the security of the current design, that the rest of your reply is more about the perceived difficulty of the fix, and that you already stated quite firmly that you have no intention to fix Notary, I think I will simply stop wasting my time here.

**Comment by endophage** [comment]
Thank you for explaining the scenario you are considering. I believe this is the first time you've clearly laid out your context so we can understand. I would like you to try and separate the 2 concepts of the CA for bootstrapping, and the scope of the repo because you're really conflating them badly.

I said we're not going to change the CA. The CA is for bootstrapping _only_. It is strictly better security than a completely untrusted download.

Separately your scoping problem, that you've now described more clearly, is a reasonable scenario. Certainly we have implemented Docker Content Trust in a way that provides a base level of security around hub repositories. We're open to having a discussion about scoping if you're willing to be a constructive participant.

The case you're describing is easily solved by creating a repository that contains all the images, differentiated by tag, that will be deployed together as a service. Some users already organized their hub repositories this way even before the introduction of Docker Content Trust.

**Comment by KellerFuchs** [comment]
> I believe this is the first time you've clearly laid out your context so we can understand.

First paragraph of my [first reply](https://github.com/docker/notary/issues/794#issuecomment-227175195).  Sorry if this was not clear enough.

> We're open to having a discussion about scoping if you're willing to be a constructive participant.

Given how much effort I put into this discussion even after being told that the scoping wouldn't be changed, I would have thought that was a given.

> The case you're describing is easily solved by creating a repository that contains all the images, differentiated by tag.

I will have to have a second read through the implementation and test whether I can do things like delegating publication power to specific tags and so on.

Thanks a lot for the reply.

**Comment by riyazdf** [comment]
For "delegating publication power to specific tags" it seems like using delegation roles with restricted paths could be helpful.

The `--paths` flag on `notary delegation add` will allow you to set a restricted set of path prefixes that the delegation role can publish to.

**Comment by ecordell** [comment]
@riyazdf @endophage I've been watching this issue with interest, because my initial evaluation of Notary/DCT left me feeling similar to @KellerFuchs - there was enough different from TUF, it seemed, to make me question whether it was actually TUF anymore.

To that end I *do* think there’s value in separating out what is TUF-as-specified (the TUF kernel, if you will) and what are nice additions that the Notary team has made in support of other goals, e.g. running a production TUF repo and supporting DCT.

Some things that come to mind that are unspecified by TUF:
  
  - The use of x.509 and the trust pinning mechanism 
  - Trust bootstrapping in general
  - The use of registry auth
  - The client/server/signer architecture
  - The changeset format and general approach to staging
  - Storing old public keys in the root metadata after rotation

This isn’t to say that these things aren’t useful or even necessary for running a reified TUF repository, simply that they’re not strictly specified and therefore some notes and clear documentation about them would be useful (or even better, IMO, some stricter separation at the package level). You could also imagine some of these things being codified in the spec at some point - in fact I think some of them should be; it would be nice if I could mix and match client and server implementations and have some guarantees of compatibility (modulo bugs).

If I understand correctly, the Notary team would like Notary to be a generally useful TUF implementation rather than simply the DCT TUF module, so it might make sense to do some refactoring in some places to make things more “batteries  removable.” For example, a standard auth interface that can be implemented to suit a user’s needs (upstreaming if appropriate), or a pluggable trust pinning mechanism (right now it’s x.509 or the highway). These changes would serve to make Notary applicable in more use cases and would help clarify in the code which parts are specializations that Notary has made to the TUF spec, since it should be clear they can be implemented in a different way if necessary.

If you agree with that general direction I’m happy to work on the things I mentioned! I can open a new issue for further discussion if that’s more appropriate.

TL;DR I think there’s some documentation/refactoring work to be done here, and I’m happy to get that ball rolling if everyone else agrees.

**Comment by endophage** [comment]
@ecordell thank you for the thoughtful input. We're happy to add more documentation so your bullet pointed list is a useful place for us to start (I'll pinch it and file an issue to track the additional docs shortly).

You are correct in your understanding of what we'd like Notary to be. DCT should represent a specific deployment of Notary, rather than being the only thing Notary is suitable for.

If you have the time to start on this is would be awesome!
