### ISSUE TITLE
Image layer verification happens with and without DCT?

### ISSUE THREAD

**Issue by innocentme1** [docker/notary#799]
So, one thing I observed is that the image layer tampering can be detected even without DCT enabled (Docker Content Trust)? I also double confirmed it from here - "https://docs.docker.com/registry/spec/api/"  Image verification section.  So, why do demos of DCT in different online videos and conferences shows that DCT enabling can detect image layer tampering? It is being done even without enabling DCT? 

Am I missing something?

**Comment by riyazdf** [comment]
Hi @innocentme1: 

Yes, as you mentioned, the docs you link specify that "Before proceeding to download the individual layers, the engine verifies the manifest’s signature, ensuring that the content was produced from a trusted source and no tampering has occurred. After each layer is downloaded, the engine verifies the digest of the layer, ensuring that the content matches that specified by the manifest."

When using DCT, we use the signed trust metadata to translate pulls-by-tag to a pull-by-digest (in a trusted manner by verifying signatures and expiries) to ensure the _first_ part of the pull is trusted -- that the tag was signed to a particular digest, which is calculated from and verified against the manifest we download first.  Once we verify the manifest, the rest of the pull-by-digest can self-verify each layer.

The "trust_sandbox" last exercise does fail without trust as well, since we modified an image layer, but you should also try modifying the manifest file (should be located at `/var/lib/registry/docker/registry/v2/blobs/sha256/eb/ebf59c538accdf160ef435f1a19938ab8c0d6bd96aef8d4ddd1b379edf15a926/data`)

**Comment by innocentme1** [comment]
@riyazdf 

Yup. I do know that the trust verifies basing on the manifest layer and then basing on the digest. But in multiple videos, I did observe people saying that this is getting failed because of DCT. For instance, in this video https://www.youtube.com/watch?v=JvjdfQC8jxM , Diogo says that "Docker Content Trust detects that layer has been tampered" which actually is not right. (Video 23.50) DCT is not detecting it , its actually being done directly by Docker engine. Right?

**Comment by endophage** [comment]
Actually, it wasn't realized the layer integrity detection wasn't being done until we added content trust and took a close look at the existing checks in docker.

However, you are correct that the layer integrity is checked even with DCT disabled. We include it because without DCT, the lack of any guarantees around the manifest make this integrity check a moot point. If I can modify the layer, I can simply modify the manifest to reference the modified layer. 

Therefore, demoing layer integrity checks _without_ DCT doesn't make sense. It's an illusion of security. Only with DCT do the layer integrity checks provide real security.

N.B. DCT basically translated the tag into a checksum, so if you're _not_ using DCT, but pulling/running/building by checksum anyway, you'll get the same level of integrity guarantee as DCT.

**Comment by innocentme1** [comment]
@endophage I totally agree with you but I just wanted to confirm that the layer verification is done even without DCT. You confirmed it now - Thank you :)
