### ISSUE TITLE
Do we support rotating the delegation key as well?

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#853]
It seems the role should be one of "snapshot", "targets", "root", or "timestamp", do we also support "delegation" role, such as 
```
notary key rotate huawei.com targets/notary/server
```

**Comment by riyazdf** [comment]
At this time we don't support delegation roles in the `key rotate` command.

For rotating specific delegation keys, the admin who holds the targets key should remove and add delegation keys with the `delegation add` and `delegation remove` commands, specifying the key IDs in the commands.

It's unclear what the best way would be to get `key rotate` to work cleanly with a given delegation role because it may contain multiple keys, so it's not clear if we should rotate all the keys or just one.

**Comment by HuKeping** [comment]
I file this issue just to make sure I haven't miss something.

You are right @riyazdf , the `delegation add` and `delegation remove` is enough at present, even for the multi tenant, the master of the tenant can use this way to rotate those compromised keys if necessary.
