### ISSUE TITLE
Change example on the content trust docs 

### ISSUE THREAD

**Issue by innocentme1** [docker/notary#876]
As described in this issue: https://github.com/docker/notary/issues/799. I feel adding an example which works "only" with DCT enabled will be good and proper (Current document has an example which works even if DCT is disabled) - Maybe an example tampering manifest file? which works only if DCT is enabled. This shows users the powers of DCT. Current example is kind of slightly misleading. It was presented right after the DCT explanation and gives an essence that the example works only with DCT enabled but infact - it is not. Initially, I am slightly confused on this too and made myself clear only after some research.

Example link:  https://docs.docker.com/engine/security/trust/trust_sandbox/

**Comment by innocentme1** [comment]
@cyli @endophage Any thoughts?

**Comment by endophage** [comment]
@innocentme1 we could definitely create a docker hub image repo for which we intentionally didn't publish any trust data, causing it to fail when DCT is enabled.

I'd be reticent to provide an example with actual tampered data because that would require bypassing a lot of safety, integrity, and consistency checks in docker hub and registry and could (as highly unlikely as it may be) result in corrupting other user data in the registry.

**Comment by innocentme1** [comment]
@endophage I am not sure if you got me right (or I got you right). I am trying to explain that we need to write a better example under the "Test with Malicious Images" section. Current example is not showing the actual DCT mechanism. That works even without DCT i.e., Image layer tampering detection works even without DCT. What DCT explicitly provides is manifest file integrity (as you know). 

So, I am suggesting to provide a manifest file integrity violation example i.e., rather than asking users to add "Malicious Data" in the normal layer , ask them to append it on the manifest layer when DCT is enabled. That gives more sense of DCT essence is what I feel. 

Please let me know, if I am still not clear.

**Comment by endophage** [comment]
I understood you. I'm just trying to think of a way to demonstrate the behaviour without actually providing a malicious/bad/broken image on the hub. The problem being the hub deduplicates data so there is always the possibility somebody later tries to push the mismatching layer and because it already exists, their new data doesn't get uploaded. Their subsequent pulls of their image would then pull the broken layer and we would have unintentionally corrupted somebody else's data.

i.e. 
  - We create a layer A and put it into the hub's data storage. We say it has the incorrect checksum ABC so that it will intentionally fail (for the trust demo in the docs) when we try and pull the image containing the layer.
  - At a later point in time, a real user creates a layer B that legitimately has checksum ABC. When they upload their layer, it's deduplicated in the back end storage because there's already an object with checksum ABC (the registry doesn't re-checksum objects already in storage, it's assumed they were written in correctly), that object is layer B.
  - When the user attempts to pull layer B, what they really pull is checksum ABC, which returns the data of layer A, preventing the user from successfully pulling their image.

Yes, I agree that checksum collisions are very, very unlikely, but on the infinitesimally small chance that it could happen, it would be a really bad experience for the user and I would imagine very frustrating to debug. Not to mention if the person debugging had no knowledge of how the data in storage came to be corrupted it could create a lot of wasted time tracking down a non-issue.

**Comment by riyazdf** [comment]
closing since there hasn't been any activity on this issue, please feel free to re-open if there is a new proposal
