### ISSUE TITLE
Why are there plaintext passwords in server-config.rethink.json file etc.?

### ISSUE THREAD

**Issue by innocentme1** [docker/notary#878]
I am not sure on why the username and passwords are stored in plaintext format in the above file. Same with the case of signer file too.

**Comment by cyli** [comment]
The compose file is just for development and testing purposes.  You should definitely use your own config with your own passwords, or add a startup script to pull it from etcd or however you set up your own system.

**Comment by innocentme1** [comment]
I dont think this particular thing was made explicit in the production precautions document : https://github.com/docker/notary/blob/master/docs/running_a_service.md 

Was it? Am I missing it?

**Comment by cyli** [comment]
Ah, apologies, we have no documentation for the rethinkDB stores yet because we are still working on support for it.

0.4 is probably the first release that we're officially going to provide support for for rethinkdb, so it will be coming.

We do have this line in the docs:

>However, for running in production, or if you just want to change those defaults on your development service, you probably want to change those defaults.

But you're right, it should specifically be added to https://github.com/docker/notary/blob/master/docs/running_a_service.md#recommendations-for-deploying-in-production, since certificates are mentioned, when we add the rethink documentation.

**Comment by innocentme1** [comment]
Yes - I saw that line. but yes - its definitely good to add that line to rethink documentation when documentation for it is made. Thanks for clarifying.

**Comment by riyazdf** [comment]
Updated checklist in https://github.com/docker/notary/issues/828 to include rethinkdb, closing this issue.
