### ISSUE TITLE
Notary push fails with HTTP 400 response body: invalid character 'B'

### ISSUE THREAD

**Issue by ashishjain14** [docker/notary#916]
I have a notary setup which uses tls and token authentication. I am able to use Notary
1) Without tls on localhost
2) With tls enabled from remote host

However I am unable to do push,pull once I enable token authentication  on notary. I am using cessanta docker-auth server and I am able to use the same with docker registry. I keep getting the following error

docker push xxxxxxxxxxx:5000/golang:test
The push refers to a repository [xxxxxxxxxxxx:5000/golang]
60506af6cb6f: Layer already exists 
3e41f9940615: Layer already exists 
dd11b45f52cb: Layer already exists 
e6dd2a623b37: Layer already exists 
c8cf6ee24805: Layer already exists 
4fe15f8d0ae6: Layer already exists 
test: digest: sha256:bba4b7325d5675baf7327f554316317469a7911f54cf70c3624c893fce5222fd size: 1572
Signing and pushing trust metadata
WARN[0000] Error while downloading remote metadata, using cached timestamp - this might not be the latest version available remotely 
WARN[0000] Error while downloading remote metadata, using cached timestamp - this might not be the latest version available remotely 
ERRO[0000] Could not publish Repository since we could not update: error parsing HTTP 400 response body: invalid character 'B' looking for beginning of value: "Bad request: invalid scope: \"repository:xxxxxxxxxxxx:5000/golang:push,pull\"\n" 
Failed to sign "xxxxxxxxxxxx:5000/golang":test - error parsing HTTP 400 response body: invalid character 'B' looking for beginning of value: "Bad request: invalid scope: \"repository:xxxxxxxxxx:5000/golang:push,pull\"\n"
error parsing HTTP 400 response body: invalid character 'B' looking for beginning of value: "Bad request: invalid scope: \"repository:xxxxxxxxxxxx:5000/golang:push,pull\"\n"

Some details on my environment
ocker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

**Comment by cyli** [comment]
Hi @ashishjain14 - sorry for the inconvenience!.

Looks like the cessanta docker auth server [does not expect the resource name to have a `server:port` number](https://github.com/cesanta/docker_auth/blob/master/auth_server/server/server.go#L171), which [does not exactly conform to the spec, as a resource name can have a hostname, which can include a port](https://github.com/docker/distribution/blob/1b9ab303a477ded9bdd3fc97e9119fa8f9e58fca/docs/spec/auth/scope.md).  

Docker registry drops the registry part, since it's assuming you are communicating with it.

Notary can't do the same, since the same server can be used for multiple registries.

Might be worth filing a bug with the auth project?

**Comment by ashishjain14** [comment]
Thanks have filed a bug with them and looks like the issue is fixed. I will close this issue now will reopen if any further help is required,

**Comment by cyli** [comment]
Thanks for the update @ashishjain14!

**Comment by ashishjain14** [comment]
Thanks for your help and prompt reply on this. BTW you know docker is amazing and you guys too :+1:

**Comment by cyli** [comment]
@ashishjain14 Thank you so much for your kind words!  Always good to hear :)
